
name: Schedule Telegram Bot

on:
  schedule:
    - cron: '32 1 * * *'  # Runs at 08:00 AM UTC
    - cron: '30 7 * * *'  # Runs at 12:30 AM UTC

jobs:
  send_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify function
        run: |
          curl https://lighthearted-travesseiro-de5c56.netlify.app/.netlify/functions/telegramBot
