
name: Schedule Telegram Bot

on:
  schedule:
    - cron: '15 2 * * *'  # Runs at 08:00 AM UTC
    - cron: '45 15 * * *'  # Runs at 12:30 AM UTC
  workflow_dispatch:  # Allow manual triggering

env:  # Define global environment variables for all jobs
  TOKEN: ${{ secrets.TOKEN }}
  CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

jobs:
  send_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify function
        run: |
          curl -X POST https://lighthearted-travesseiro-de5c56.netlify.app/.netlify/functions/telegramBot
