
name: Schedule Telegram Bot

on:
  schedule:
    - cron: '22 8 * * *'  # Runs at 08:00 AM UTC
    - cron: '30 9 * * *'  # Runs at 12:30 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  send_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify function
        run: |
          curl -X POST https://lighthearted-travesseiro-de5c56.netlify.app/.netlify/functions/telegramBot
